version: "3"

services:
  postgres:
    image: postgres
    container_name: camunda_postgres
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: ghjvtntq
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
